version: "3"
services:
  webapp:
    image: shirugaron/xuletre-webapp:2.0.0
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  monitorapp:
    image: shirugaron/xuletre-monitor:2.0.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8090:8090"
    networks:
      - webnet
networks:
  webnet: